Title =  "IT侠的博客"
BaseUrl = "https://itxia.github.io/soft/"
Theme =  "hugo-theme-next"

BuildDrafts =  false
CanonifyUrls =  true
DefaultContentLanguage = "zh"
DisablePathToLower =  true
HasCJKLanguage = true
MetaDataFormat =  "yaml"
LanguageCode = "zh-CN"
PaginatePath =  "p"
Paginate = 8

[Params]
  Introduce = ""
  Description = "IT侠博客专为软件教学系列的文档"
  Keywords =  ""
  Subtitle = "For 软件教学系列"
  Imglogo = "/img/github.ico"
  AuthorImg = false
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  Fancybox = false

[Author]
  Name = "ITxia & More"

[Params.Share]
  Baidu = false

[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "分类"
  Pre = "folder"
  URL = "/categories/"
  Weight = 3
[[Menu.Main]]
  Name = "标签"
  Pre = "tags"
  URL = "/tags/"
  Weight = 4
[[Menu.Main]]
  Name = "归档"
  Pre = "archive"
  URL = "/post/"
  Weight = 5

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/itxia/"

[markup]
  [markup.highlight]
    lineNos = true
    style = "monokailight"
